CREATE TEXT SEARCH CONFIGURATION BUSCA (COPY = portuguese);
ALTER TEXT SEARCH CONFIGURATION BUSCA ALTER MAPPING FOR hword, hword_part, word WITH portuguese_stem;

CREATE TABLE IF NOT EXISTS person (
    id VARCHAR(36),
    apelido VARCHAR(32) CONSTRAINT ID_PK PRIMARY KEY,
    nome VARCHAR(100),
    nascimento CHAR(10),
    stack VARCHAR(1024),
    BUSCA TSVECTOR GENERATED ALWAYS AS (
        TO_TSVECTOR('BUSCA', NOME || ' ' || APELIDO || ' ' || STACK)
    ) STORED
);

CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_person_ID ON person USING HASH (ID);
CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_person_BUSCA ON person USING GIN (BUSCA);